namespace ScoreSharpTestData.Entity;

public class EcardNewCaseRequest
{

    public string APPLY_NO { get; set; }
    public string ID_TYPE { get; set; }
    public string CREDIT_ID { get; set; }
    public string CARD_OWNER { get; set; }
    public string MCARD_SER { get; set; }
    public string FORM_ID { get; set; }
    public string CH_NAME { get; set; }
    public string SEX { get; set; }
    public string BIRTHDAY { get; set; }
    public string ENG_NAME { get; set; }
    public string BIRTH_PLACE { get; set; }
    public string BIRTH_PLACE_OTHER { get; set; }
    public string NATIONALITY { get; set; }
    public string P_ID { get; set; }
    public string P_ID_GETDATE { get; set; }
    public string P_ID_GETADDRNAME { get; set; }
    public string P_ID_STATUS { get; set; }
    public string REG_ZIP { get; set; }
    public string REG_ADDR_CITY { get; set; }
    public string REG_ADDR_DIST { get; set; }
    public string REG_ADDR_RD { get; set; }
    public string REG_ADDR_LN { get; set; }
    public string REG_ADDR_ALY { get; set; }
    public string REG_ADDR_NO { get; set; }
    public string REG_ADDR_SUBNO { get; set; }
    public string REG_ADDR_F { get; set; }
    public string REG_ADDR_OTHER { get; set; }
    public string HOME_ZIP { get; set; }
    public string HOME_ADDR_CITY { get; set; }
    public string HOME_ADDR_DIST { get; set; }
    public string HOME_ADDR_RD { get; set; }
    public string HOME_ADDR_LN { get; set; }
    public string HOME_ADDR_ALY { get; set; }
    public string HOME_ADDR_NO { get; set; }
    public string HOME_ADDR_SUBNO { get; set; }
    public string HOME_ADDR_F { get; set; }
    public string HOME_ADDR_OTHER { get; set; }
    public string BILL_TO_ADDR { get; set; }
    public string CARD_TO_ADDR { get; set; }
    public string CELL_PHONE_NO { get; set; }
    public string EMAIL { get; set; }
    public string JOB_TYPE { get; set; }
    public string JOB_TYPE_OTHER { get; set; }
    public string JOB_LV { get; set; }
    public string COMP_NAME { get; set; }
    public string COMP_TEL_NO { get; set; }
    public string COMP_ZIP { get; set; }
    public string COMP_ADDR_CITY { get; set; }
    public string COMP_ADDR_DIST { get; set; }
    public string COMP_ADDR_RD { get; set; }
    public string COMP_ADDR_LN { get; set; }
    public string COMP_ADDR_ALY { get; set; }
    public string COMP_ADDR_NO { get; set; }
    public string COMP_ADDR_SUBNO { get; set; }
    public string COMP_ADDR_F { get; set; }
    public string COMP_ADDR_OTHER { get; set; }
    public string SALARY { get; set; }
    public string MAIN_INCOME { get; set; }
    public string MAIN_INCOME_OTHER { get; set; }
    public string ACCEPT_DM_FLG { get; set; }
    public string M_PROJECT_CODE_ID { get; set; }
    public string PROM_UNIT_SER { get; set; }
    public string PROM_USER_NAME { get; set; }
    public string AGREE_MARKETING_FLG { get; set; }
    public string NOT_ACCEPT_EPAPAER_FLG { get; set; }
    public string FAMILY6_AGE { get; set; }
    public string CHG_CARD_ADDR { get; set; }
    public string BILL_TYPE { get; set; }
    public string AUTO_FLG { get; set; }
    public string ACCT_NO { get; set; }
    public string PAY_WAY { get; set; }
    public string SOURCE_TYPE { get; set; }
    public string SOURCE_IP { get; set; }
    public string OTP_MOBILE_PHONE { get; set; }
    public string OTP_TIME { get; set; }
    public string DIGI_CARD_FLG { get; set; }
    public string CARD_KIND { get; set; }
    public string APPLICATION_FILE_NAME { get; set; }
    public string APPENDIX_FLG { get; set; }
    public string MYDATA_NO { get; set; }
    public string CARD_ADDR { get; set; }
    public string KYC_CHG_FLG { get; set; }
    public string CONSUM_NOTICE_FLG { get; set; }
    public string UUID { get; set; }
    public string DEMAND_CURR_BAL { get; set; }
    public string TIME_CURR_BAL { get; set; }
    public string DEMAND_90DAY_BAL { get; set; }
    public string TIME_90DAY_BAL { get; set; }
    public string BAL_UPD_DATE { get; set; }
    public string STUDENT_FLG { get; set; }
    public string PARENT_NAME { get; set; }
    public string PARENT_HOME_TEL_NO { get; set; }
    public string PARENT_HOME_ZIP { get; set; }
    public string PARENT_HOME_ADDR_CITY { get; set; }
    public string PARENT_HOME_ADDR_DIST { get; set; }
    public string PARENT_HOME_ADDR_RD { get; set; }
    public string PARENT_HOME_ADDR_LN { get; set; }
    public string PARENT_HOME_ADDR_ALY { get; set; }
    public string PARENT_HOME_ADDR_NO { get; set; }
    public string PARENT_HOME_ADDR_SUBNO { get; set; }
    public string PARENT_HOME_ADDR_F { get; set; }
    public string PARENT_HOME_ADDR_OTHER { get; set; }
    public string EDUCATION { get; set; }
    public string REG_TEL_NO { get; set; }
    public string HOME_TEL_NO { get; set; }
    public string HOME_ADDR_COND { get; set; }
    public string PRIMARY_SCHOOL { get; set; }
    public string COMP_ID { get; set; }
    public string JOB_TITLE { get; set; }
    public string JOB_YEAR { get; set; }
    public string AL_NO { get; set; }
    public string APPENDIX_FILE_NAME_01 { get; set; }
    public string APPENDIX_FILE_NAME_02 { get; set; }
    public string APPENDIX_FILE_NAME_03 { get; set; }
    public string APPENDIX_FILE_NAME_04 { get; set; }
    public string APPENDIX_FILE_NAME_05 { get; set; }
    public string APPENDIX_FILE_NAME_06 { get; set; }
    public string APPENDIX_FILE_NAME_07 { get; set; }
    public string APPENDIX_FILE_NAME_08 { get; set; }
}
