// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScoreSharpTestData.Models;

public partial class AuthAction
{
    /// <summary>
    /// 英數字，API Action 名稱
    /// </summary>
    public string ActionId { get; set; }

    /// <summary>
    /// 中文，前端顯示功能
    /// </summary>
    public string ActionName { get; set; }

    /// <summary>
    /// Y/N，如果是Y 不檢查全縣
    /// </summary>
    public string IsCommon { get; set; }

    /// <summary>
    /// Y/N
    /// </summary>
    public string IsActive { get; set; }

    /// <summary>
    /// 新增員工
    /// </summary>
    public string AddUserId { get; set; }

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime AddTime { get; set; }

    /// <summary>
    /// 修正員工
    /// </summary>
    public string UpdateUserId { get; set; }

    /// <summary>
    /// 修正時間
    /// </summary>
    public DateTime? UpdateTime { get; set; }

    /// <summary>
    /// 關聯Auth_Router
    /// </summary>
    public string RouterId { get; set; }
}