// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScoreSharpTestData.Models;

/// <summary>
/// 使用者
/// </summary>
public partial class AuthUser
{
    /// <summary>
    /// 使用者帳號，目前來源為 AD Server
    /// </summary>
    public string UserId { get; set; }

    /// <summary>
    /// 授權額度
    /// </summary>
    public int AuthorizationAmount { get; set; }

    /// <summary>
    /// 是否啟用，Y | N
    /// </summary>
    public string IsActive { get; set; }

    /// <summary>
    /// 新增員工
    /// </summary>
    public string AddUserId { get; set; }

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime AddTime { get; set; }

    /// <summary>
    /// 修正員工
    /// </summary>
    public string UpdateUserId { get; set; }

    /// <summary>
    /// 修正時間
    /// </summary>
    public DateTime? UpdateTime { get; set; }

    /// <summary>
    /// 使用者姓名
    /// </summary>
    public string UserName { get; set; }
}