// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Dapper;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using ScoreSharpTestData.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace ScoreSharpTestData.Models
{
    public partial interface IScoreSharpContextProcedures
    {
        Task<List<Usp_GetApplyCreditCardInfoWithParamsResult>> Usp_GetApplyCreditCardInfoWithParamsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<(List<Usp_GetApplyCreditCardInfoWithPrimaryAddressByApplyNoResult1> Result1, List<Usp_GetApplyCreditCardInfoWithPrimaryAddressByApplyNoResult2> Result2)> Usp_GetApplyCreditCardInfoWithPrimaryAddressByApplyNoAsync(string applyNo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
