// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScoreSharpTestData.Models;

/// <summary>
/// 徵審待辦_申請信用卡地址資料
/// </summary>
public partial class ReviewerPeddingApplyCreditCardInfoAddress
{
    /// <summary>
    /// 申請書編號，PK
    /// </summary>
    public string ApplyNo { get; set; }

    /// <summary>
    /// 地址類型，
    /// 1.正卡人戶籍地址
    /// 2.正卡人居住地址
    /// 3.正卡人公司地址
    /// 4.正卡人家長地址
    /// 
    /// </summary>
    public int AddressType { get; set; }

    /// <summary>
    /// 身分證字號，當地址類型為 1、2、4、5需有值
    /// </summary>
    public string Id { get; set; }

    /// <summary>
    /// 公司統一編號，當地址類型為 5需有值
    /// </summary>
    public string CompId { get; set; }

    /// <summary>
    /// 郵遞區號
    /// </summary>
    public string ZipCode { get; set; }

    /// <summary>
    /// 縣市
    /// </summary>
    public string City { get; set; }

    /// <summary>
    /// 區域
    /// </summary>
    public string District { get; set; }

    /// <summary>
    /// 街道
    /// </summary>
    public string Road { get; set; }

    /// <summary>
    /// 巷
    /// </summary>
    public string Lane { get; set; }

    /// <summary>
    /// 弄
    /// </summary>
    public string Alley { get; set; }

    /// <summary>
    /// 號
    /// </summary>
    public string Number { get; set; }

    /// <summary>
    /// 之號
    /// </summary>
    public string SubNumber { get; set; }

    /// <summary>
    /// 樓層
    /// </summary>
    public string Floor { get; set; }

    /// <summary>
    /// 其他
    /// </summary>
    public string Other { get; set; }
}