// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScoreSharpTestData.Models;

public partial class ReviewerApplyCreditCardInfoPrimary
{
    /// <summary>
    /// 申請書編號：範例20180625A0001
    /// </summary>
    public string ApplyNo { get; set; }

    /// <summary>
    /// 申請日期
    /// </summary>
    public DateTime ApplyDate { get; set; }

    /// <summary>
    /// 卡片狀態，查看附件-卡片狀態碼
    /// </summary>
    public int CardStatus { get; set; }

    /// <summary>
    /// 徵信代碼：如A02為原卡友，關聯SetUp_
    /// </summary>
    public string CreditCheckCode { get; set; }

    /// <summary>
    /// 身分證驗證結果-正/附卡：聯徵查回後會有相關資訊可入
    /// </summary>
    public string IdcheckResultChecked { get; set; }

    /// <summary>
    /// 申請卡別：以&apos;/&apos;串接，如JA00/JC00，關聯　SetUp_Card
    /// </summary>
    public string ApplyCardType { get; set; }

    /// <summary>
    /// 客服備註
    /// </summary>
    public string CustomerServiceNotes { get; set; }

    /// <summary>
    /// 家族訊息正/附卡：資料來源總行業管部自建資料庫 / Y 、N
    /// </summary>
    public string FamilyMessageChecked { get; set; }

    /// <summary>
    /// 是否重複申請件：此欄位包含申請人是否曾有申請本行信用卡+現在是否為本行信用卡流通戶 / Y 、N
    /// </summary>
    public string IsRepeatApply { get; set; }

    /// <summary>
    /// 正附卡：1. 正卡 2. 附卡 3. 正卡+附卡 4. 附卡2  5. 正卡+附卡2
    /// </summary>
    public int CardOwner { get; set; }

    /// <summary>
    /// 客戶特殊註記
    /// </summary>
    public string CustomerSpecialNotes { get; set; }

    /// <summary>
    /// 用API方式以身分證字號查詢資料庫，檢核是否命中情形，資料庫來源為業務管理部 / Y 、N
    /// </summary>
    public string Checked929 { get; set; }

    /// <summary>
    /// 身份別：1. 新戶 2.原持卡人 3. 卡友 4. 存戶 5. 持他行卡 6. 自然人憑證
    /// </summary>
    public int Idtype { get; set; }

    /// <summary>
    /// 案件種類，如一般件
    /// </summary>
    public int CaseType { get; set; }

    /// <summary>
    /// 長循分期戶 ： Y 、N
    /// </summary>
    public string LongTerm { get; set; }

    /// <summary>
    /// 用API方式以身分證字號查詢資料庫，檢核是否命中情形，資料庫來源為法令遵循部 / Y 、N
    /// </summary>
    public string WarningListChecked { get; set; }

    /// <summary>
    /// 1. 現由文彬依聯徵查回結果提供 2. Y 、N
    /// </summary>
    public string OriginCardholderJcicnotes { get; set; }

    /// <summary>
    /// 分行客戶：用API方式以查詢分行平台資料，分行平台資訊來源為資訊部，Y 、N
    /// </summary>
    public string BranchCustomer { get; set; }

    /// <summary>
    /// 姓名核驗正附卡 ：1. 於敦陽系統之姓名檢核   2. Y 、N
    /// </summary>
    public string NameChecked { get; set; }

    /// <summary>
    /// 審查人員編號
    /// </summary>
    public string ReviewerEmpNo { get; set; }

    /// <summary>
    /// 黑名單註記：查詢paperless內建資料庫是否有資料相符情形 / Y 、N
    /// </summary>
    public string BlackListNote { get; set; }

    /// <summary>
    /// 評分結果：從授信政策科
    /// </summary>
    public int CreditLimitRatingAdvice { get; set; }

    /// <summary>
    /// 洗防風險等級：由AML-KYC提供風險等級
    /// </summary>
    public string AmlriskLevel { get; set; }

    /// <summary>
    /// 核准人員員編
    /// </summary>
    public string ApproveEmpNo { get; set; }

    /// <summary>
    /// 中文姓名
    /// </summary>
    public string Chname { get; set; }

    /// <summary>
    /// 性別：1.男生 2. 女生
    /// </summary>
    public int Sex { get; set; }

    /// <summary>
    /// 生日：民國格式為 YYYMMDD
    /// </summary>
    public string BirthDay { get; set; }

    /// <summary>
    /// 英文名稱
    /// </summary>
    public string Enname { get; set; }

    /// <summary>
    /// 身份證字號
    /// </summary>
    public string Id { get; set; }

    /// <summary>
    /// 身分證發證日期：民國格式為 YYYMMDD
    /// </summary>
    public string IdissueDate { get; set; }

    /// <summary>
    /// 身分證發證地點：關聯 SetUp_IDCardRenewalLocation
    /// </summary>
    public string IdcardRenewalLocationCode { get; set; }

    /// <summary>
    /// 身分證請領狀態：1. 初發, 2. 補發, 3. 換發
    /// </summary>
    public int IdtakeStatus { get; set; }

    /// <summary>
    /// 國籍：關聯 SetUp_Citizenship
    /// </summary>
    public string CitizenshipCode { get; set; }

    /// <summary>
    /// 婚姻狀況：1. 已婚, 2. 未婚, 3. 其他
    /// </summary>
    public int MarriageState { get; set; }

    /// <summary>
    /// 教育程度：1. 博士, 2. 碩士, 3. 大學, 4. 專科, 5. 高中職, 6. 其他
    /// </summary>
    public int Education { get; set; }

    /// <summary>
    /// 畢業國小
    /// </summary>
    public string GraduatedElementarySchool { get; set; }

    /// <summary>
    /// 行動電話
    /// </summary>
    public string Mobile { get; set; }

    /// <summary>
    /// E-MAIL
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// 帳單地址：1. 同戶籍, 2. 同居住, 3. 公司
    /// </summary>
    public int BillAddress { get; set; }

    /// <summary>
    /// 寄卡地址
    /// </summary>
    public int SendCardAddress { get; set; }

    /// <summary>
    /// 戶籍電話
    /// </summary>
    public string HouseRegPhone { get; set; }

    /// <summary>
    /// 居住電話
    /// </summary>
    public string LivePhone { get; set; }

    /// <summary>
    /// 居住地所有權人：1. 本人, 2. 配偶, 3. 父母, 4. 子女, 5. 親戚, 6. 朋友, 7. 其他
    /// </summary>
    public int LiveOwner { get; set; }

    /// <summary>
    /// 居住年數
    /// </summary>
    public int LiveYear { get; set; }

    /// <summary>
    /// 推廣單位
    /// </summary>
    public string PromotionUnit { get; set; }

    /// <summary>
    /// 推廣人員
    /// </summary>
    public string PromotionUser { get; set; }

    /// <summary>
    /// 安麗編號
    /// </summary>
    public string AliNo { get; set; }

    /// <summary>
    /// 居留證發證日期 (格式: YYYYMMDD)
    /// </summary>
    public string ResidencePermitIssueDate { get; set; }

    /// <summary>
    /// 護照號碼
    /// </summary>
    public string PassportNo { get; set; }

    /// <summary>
    /// 護照日期 (格式: YYYYMMDD)
    /// </summary>
    public string PassportDate { get; set; }

    /// <summary>
    /// 外籍人士停留期限 (格式: YYYYMMDD)
    /// </summary>
    public string ExpatValidityPeriod { get; set; }

    /// <summary>
    /// 敦陽系統黑名單查詢記錄 (Y/N)
    /// </summary>
    public string IsDunyangBlackList { get; set; }

    /// <summary>
    /// 姓名檢核理由代碼，敦陽系統黑名單是否相符= Y 和 姓名檢核 = Y 要有理由碼
    /// 1. PEP
    /// 2. 要再問
    /// 3. 黑名單
    /// 4. 負面新聞
    /// 5. 無
    /// 6. RCA
    /// 7. 國內PEP
    /// 8. 國外PEP
    /// 9. 國際組織PEP
    /// 10. 卸任PEP
    /// 
    /// </summary>
    public int? NameCheckedReasonCode { get; set; }

    /// <summary>
    /// 當前或曾為PEP身分 (Y/N)，敦陽系統黑名單是否相符= Y 和 姓名檢核 = Y 需填寫
    /// </summary>
    public string IsrcaforCurrentPrp { get; set; }

    /// <summary>
    /// 卸任PEP種類：1. 國內 2.國外 3.國際組織 / 敦陽系統黑名單是否相符= Y 和 姓名檢核 = Y 需填寫
    /// </summary>
    public int? ResignPepkind { get; set; }

    /// <summary>
    /// 擔任PEP範圍:
    /// 不滿2年
    /// 滿兩年但不滿四年
    /// 滿4年 / 敦陽系統黑名單是否相符= Y 和 姓名檢核 = Y 需填寫
    /// </summary>
    public int? Peprange { get; set; }

    /// <summary>
    /// 現任職位是否與PEP職位相關 (Y/N)，敦陽系統黑名單是否相符= Y 和 姓名檢核 = Y 需填寫
    /// </summary>
    public string IsCurrentPositionRelatedPepposition { get; set; }

    /// <summary>
    /// 出生地國籍：1. 中華民國 2. 其他
    /// </summary>
    public int BirthCitizenshipCode { get; set; }

    /// <summary>
    /// 出生地國籍_其他：當出生地國籍為其他時使用
    /// </summary>
    public string BirthCitizenshipCodeOther { get; set; }

    /// <summary>
    /// 是否FATCA身份 (Y/N)，當國籍 = 美國時候預設為 Y
    /// </summary>
    public string IsFatcaidentity { get; set; }

    /// <summary>
    /// 社會安全號碼，FATCA身份=Y，徵審人員會去跟客人要此值
    /// </summary>
    public string SocialSecurityCode { get; set; }

    /// <summary>
    /// 公司名稱
    /// </summary>
    public string CompName { get; set; }

    /// <summary>
    /// 公司統一編號
    /// </summary>
    public string CompId { get; set; }

    /// <summary>
    /// 公司職稱
    /// </summary>
    public string CompJobTitle { get; set; }

    /// <summary>
    /// 公司年資
    /// </summary>
    public int? CompSeniority { get; set; }

    /// <summary>
    /// 公司電話
    /// </summary>
    public string CompPhone { get; set; }

    /// <summary>
    /// AML職業別：關聯  SetUp_AMLProfession
    /// </summary>
    public int? AmlprofessionCode { get; set; }

    /// <summary>
    /// AML職業別版本、關聯SetUp_AMLProfession
    /// </summary>
    public string AmlprofessionCodeVersion { get; set; }

    /// <summary>
    /// AML職業別_其他
    /// </summary>
    public string AmlprofessionOther { get; set; }

    /// <summary>
    /// AML職級別：關聯 SetUp_AMLJobLevel
    /// </summary>
    public int? AmljobLevelCode { get; set; }

    /// <summary>
    /// 公司行業別
    /// 1. 營造/製造/運輸業
    /// 2. 一般商業
    /// 3. 休閒/娛樂/服務業
    /// 4. 軍警消防業
    /// 5. 非營利團體
    /// 6. 學生
    /// 7. 自由業/其他
    /// 
    /// </summary>
    public int? CompTrade { get; set; }

    /// <summary>
    /// 公司職級別
    /// 1. 駕駛人員
    /// 2. 服務生/門市人員
    /// 3. 專業人員
    /// 4. 專業技工
    /// 5. 業務人員
    /// 6. 一般職員
    /// 7. 主管階層
    /// 8. 股東/董事/負責人
    /// 9. 家管/其他
    /// 
    /// </summary>
    public int? CompJobLevel { get; set; }

    /// <summary>
    /// 現職月收入(元)
    /// </summary>
    public int? CurrentMonthIncome { get; set; }

    /// <summary>
    /// 所得及資金來源 (請參考Setup_MainIncomeAndFund表格、需符合Paperless「主要所得及資金來源勾選」，多選選項以逗號(,)區隔)
    /// </summary>
    public string MainIncomeAndFundCodes { get; set; }

    /// <summary>
    /// 主要收入_其他
    /// </summary>
    public string MainIncomeAndFundOther { get; set; }

    /// <summary>
    /// 是否學生身份 (Y: 是, N: 否)
    /// </summary>
    public string IsStudent { get; set; }

    /// <summary>
    /// 學生就讀學校 (IsStudent = Y 才有值)
    /// </summary>
    public string StudSchool { get; set; }

    /// <summary>
    /// 學生預定畢業日期 (IsStudent = Y 才有值, 格式: YYYYMMDD)
    /// </summary>
    public string StudScheduledGraduationDate { get; set; }

    /// <summary>
    /// 家長姓名
    /// </summary>
    public string ParentName { get; set; }

    /// <summary>
    /// 家長電話 (可以行動電話或家電電話)
    /// </summary>
    public string ParentPhone { get; set; }

    /// <summary>
    /// 學生申請人與本人關係 (1: 父母, 2: 學生)
    /// </summary>
    public int? StudentApplicantRelationship { get; set; }

    /// <summary>
    /// 使用者來源IP位置 (E-CARD填寫)
    /// </summary>
    public string UserSourceIp { get; set; }

    /// <summary>
    /// OTP時間 (E-CARD填寫)
    /// </summary>
    public DateTime? Otptime { get; set; }

    /// <summary>
    /// OTP手機號碼 (E-CARD填寫)
    /// </summary>
    public string Otpmobile { get; set; }

    /// <summary>
    /// IP比對結果 (Y/N)
    /// </summary>
    public string Ipchecked { get; set; }

    /// <summary>
    /// 快辦件手機號碼相同 (Y: 是, N: 否)
    /// </summary>
    public string IsEqualFastCaseMobile { get; set; }

    /// <summary>
    /// 快辦件E-Mail相同 (Y: 是, N: 否)
    /// </summary>
    public string IsEqualFastCaseEmail { get; set; }

    /// <summary>
    /// 與行內IP相同 (Y: 是, N: 否)
    /// </summary>
    public string IsEqualInternalIp { get; set; }

    /// <summary>
    /// B68無擔保掛帳金額
    /// </summary>
    public int? B68unsecuredCreditAmount { get; set; }

    /// <summary>
    /// 首刷禮代碼 (E-CARD填寫)
    /// </summary>
    public string FirstBrushingGiftCode { get; set; }

    /// <summary>
    /// 本人是否同意提供資料予聯名認同集團 (Y: 是, N: 否)
    /// </summary>
    public string IsAgreeDataOpen { get; set; }

    /// <summary>
    /// 是否綁定消費通知 (Y: 是, N: 否)
    /// </summary>
    public string IsPayNoticeBind { get; set; }

    /// <summary>
    /// 專案代號 (請參考Setup_ProjectCode)
    /// </summary>
    public string ProjectCode { get; set; }

    /// <summary>
    /// 表單代號 (表單學習用，由資處定義)
    /// </summary>
    public string FormCode { get; set; }

    /// <summary>
    /// 是否同意提供資料供本行進行行銷 (Y: 是, N: 否)
    /// </summary>
    public string IsAgreeMarketing { get; set; }

    /// <summary>
    /// 是否同意悠遊卡自動加值預設設定 (Y: 是, N: 否)
    /// </summary>
    public string IsAcceptEasyCardDefaultBonus { get; set; }

    /// <summary>
    /// 帳單形式 (1：電子帳單、2：簡訊帳單、3：紙本帳單、4：LINE帳單
    /// )
    /// </summary>
    public int BillType { get; set; }

    /// <summary>
    /// 是否申請自動扣款 (Y: 是, N: 否)
    /// </summary>
    public string IsApplyAutoDeduction { get; set; }

    /// <summary>
    /// 自動扣繳帳戶-銀行存摺帳號
    /// </summary>
    public string AutoDeductionBankAccount { get; set; }

    /// <summary>
    /// 自動扣繳帳戶-扣款方式 (10,最低 20,全額)
    /// </summary>
    public int? AutoDeductionPayType { get; set; }

    /// <summary>
    /// 進件方式
    /// 1. 親訪親簽
    /// 2. 親訪未見親簽
    /// 3. 設攤親簽
    /// 4. 設為未見親簽
    /// 5. 自來件
    /// 6. 電話行銷
    /// 
    /// </summary>
    public int? AcceptType { get; set; }

    /// <summary>
    /// 申請卡種 ( 1: 實體, 2: 數位, 3: 實體+數位)
    /// </summary>
    public int ApplyCardKind { get; set; }

    /// <summary>
    /// 申請書檔名
    /// </summary>
    public string ApplicationFileName { get; set; }

    /// <summary>
    /// MyData案件編號：當附件註記為2：MYDATA後補時，本欄位必定有值
    /// </summary>
    public string MyDataCaseNo { get; set; }

    /// <summary>
    /// 是否轉換卡別：Y、N，紙本案件，申請書上可幫客人轉換卡別
    /// </summary>
    public string IsConvertCard { get; set; }

    /// <summary>
    /// 來源：1: Ecard, 2: APP, 3: 紙本
    /// </summary>
    public int Source { get; set; }

    /// <summary>
    /// 居留證背面號碼：前兩碼大寫英文 + 8 碼數字，範例ＹＺ80000001
    /// </summary>
    public string ResidencePermitBackendNum { get; set; }

    /// <summary>
    /// 是否為永久居留證
    /// 1. 配合法遵部政策，新增欄位。
    /// 2. 欄位用拉霸方式選擇，Y/N，預設為N。
    /// 3. 如為{N}，則須鍵入外籍人士指定效期。
    /// 
    /// </summary>
    public string IsForeverResidencePermit { get; set; }

    /// <summary>
    /// 居留證期限：格式 YYYYMMDD
    /// </summary>
    public string ResidencePermitDeadline { get; set; }
}