// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScoreSharpTestData.Models;

/// <summary>
/// 徵審代辦申請信用卡任務非原卡友_錯誤Log
/// </summary>
public partial class ReviewerPeddingApplyCardCheckJobForNotA02ErrorLog
{
    /// <summary>
    /// PK，字增
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// E-CARD申請書編號，
    /// 與ReviewerPedding_ApplyCardCheckJobForNotA02 關聯
    /// </summary>
    public string ApplyNo { get; set; }

    /// <summary>
    /// 錯誤訊息
    /// </summary>
    public string ErrorMesaage { get; set; }

    /// <summary>
    /// 創建時間
    /// </summary>
    public DateTime AddTime { get; set; }
}