// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScoreSharpTestData.Models;

/// <summary>
/// 信用卡優惠辦法
/// </summary>
public partial class SetUpCardPromotion
{
    /// <summary>
    /// 優惠辦法代碼，範例 : 0001
    /// </summary>
    public string CardPromotionCode { get; set; }

    /// <summary>
    /// 優惠辦法名稱
    /// </summary>
    public string CardPromotionName { get; set; }

    /// <summary>
    /// 是否啟用，Y | N
    /// </summary>
    public string IsActive { get; set; }

    /// <summary>
    /// 正卡使用POT，範例 : 01
    /// </summary>
    public string PrimaryCardUsedPot { get; set; }

    /// <summary>
    /// 附卡使用POT，範例 : 01
    /// </summary>
    public string SupplementaryCardUsedPot { get; set; }

    /// <summary>
    /// 使用POT截止月份，範例 : 01
    /// </summary>
    public string UsedPotexpiryMonth { get; set; }

    /// <summary>
    /// 正卡預留POT，範例 : 01
    /// </summary>
    public string PrimaryCardReservedPot { get; set; }

    /// <summary>
    /// 附卡預留POT，範例 : 01
    /// </summary>
    public string SupplementaryCardReservedPot { get; set; }

    /// <summary>
    /// 預留優惠期限(月)，範例 : 01
    /// </summary>
    public string ReservePromotionPeriod { get; set; }

    /// <summary>
    /// 利率，範例 : 12.22
    /// </summary>
    public decimal? InterestRate { get; set; }

    /// <summary>
    /// 新增員工
    /// </summary>
    public string AddUserId { get; set; }

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime AddTime { get; set; }

    /// <summary>
    /// 修正員工
    /// </summary>
    public string UpdateUserId { get; set; }

    /// <summary>
    /// 修正時間
    /// </summary>
    public DateTime? UpdateTime { get; set; }
}