// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScoreSharpTestData.Models;

public partial class SetUpAddressInfo
{
    /// <summary>
    /// PK
    /// </summary>
    public string SeqNo { get; set; }

    /// <summary>
    /// 郵遞區號
    /// </summary>
    public string Zipcode { get; set; }

    /// <summary>
    /// 縣市，例如新北市
    /// </summary>
    public string City { get; set; }

    /// <summary>
    /// 區域，例如蘆洲區
    /// </summary>
    public string Area { get; set; }

    /// <summary>
    /// 街道
    /// </summary>
    public string Road { get; set; }

    /// <summary>
    /// 號判斷郵遞區號規則
    /// </summary>
    public string Scope { get; set; }

    public string IsActive { get; set; }
}