// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScoreSharpTestData.Models;

/// <summary>
/// 判斷適用利率額度
/// </summary>
public partial class SetUpApplicableInterestRateLimit
{
    /// <summary>
    /// PK
    /// </summary>
    public Guid SeqNo { get; set; }

    /// <summary>
    /// 判斷適用利率額度，預設一筆且只能有一筆
    /// </summary>
    public int ApplicableInterestRateLimit { get; set; }

    /// <summary>
    /// 修正員工
    /// </summary>
    public string UpdateUserId { get; set; }

    /// <summary>
    /// 修正時間
    /// </summary>
    public DateTime? UpdateTime { get; set; }
}