// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScoreSharpTestData.Models;

/// <summary>
/// AML職級別
/// </summary>
public partial class SetUpAmljobLevel
{
    /// <summary>
    /// AML職級別代碼，範例: 1
    /// </summary>
    public string AmljobLevelCode { get; set; }

    /// <summary>
    /// AML職級別名稱
    /// </summary>
    public string AmljobLevelName { get; set; }

    /// <summary>
    /// 是否為高階管理人，Y | N
    /// </summary>
    public string IsSeniorManagers { get; set; }

    /// <summary>
    /// 是否啟用，Y | N
    /// </summary>
    public string IsActive { get; set; }

    /// <summary>
    /// 新增員工
    /// </summary>
    public string AddUserId { get; set; }

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime AddTime { get; set; }

    /// <summary>
    /// 修正員工
    /// </summary>
    public string UpdateUserId { get; set; }

    /// <summary>
    /// 修正時間
    /// </summary>
    public DateTime? UpdateTime { get; set; }
}