// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScoreSharpTestData.Models;

/// <summary>
/// 申請書類別_卡片_關聯表
/// </summary>
public partial class SetUpApplicationCategoryCard
{
    /// <summary>
    /// PK
    /// </summary>
    public int SeqNo { get; set; }

    /// <summary>
    /// BINCode，範例：33456789
    /// </summary>
    public string Bincode { get; set; }

    /// <summary>
    /// 申請書類別代碼，範例：0123
    /// </summary>
    public string ApplicationCategoryCode { get; set; }

    /// <summary>
    /// 新增員工
    /// </summary>
    public string AddUserId { get; set; }

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime AddTime { get; set; }
}