// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScoreSharpTestData.Models;

/// <summary>
/// 卡片種類_優惠辦法關聯表
/// </summary>
public partial class SetUpCardCardPromotion
{
    /// <summary>
    /// PK
    /// </summary>
    public int SeqNo { get; set; }

    /// <summary>
    /// BINCode，範例：JST65，關聯 SetUp_Card
    /// </summary>
    public string Bincode { get; set; }

    /// <summary>
    /// 優惠辦法代碼，範例：JST65，關聯 SetUp_CardPromotion
    /// </summary>
    public string CardPromotionCode { get; set; }

    /// <summary>
    /// 新增員工
    /// </summary>
    public string AddUserId { get; set; }

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime AddTime { get; set; }
}