// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScoreSharpTestData.Models;

public partial class SystemDeleteLog
{
    /// <summary>
    /// PK
    /// </summary>
    public int SeqNo { get; set; }

    /// <summary>
    /// 刪除資料的資料表名稱
    /// </summary>
    public string TableName { get; set; }

    /// <summary>
    /// 原始資料，儲存格式為 Json
    /// </summary>
    public string OriginData { get; set; }

    /// <summary>
    /// 刪除使用者Id
    /// </summary>
    public string DeleteUserId { get; set; }

    public DateTime DeleteTime { get; set; }
}