// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ScoreSharpTestData.Models
{
    public partial class Usp_GetApplyCreditCardInfoWithPrimaryAddressByApplyNoResult2
    {
        public string ApplyNo { get; set; }
        public int AddressType { get; set; }
        public string ID { get; set; }
        public string CompID { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Road { get; set; }
        public string Lane { get; set; }
        public string Alley { get; set; }
        public string Number { get; set; }
        public string SubNumber { get; set; }
        public string Floor { get; set; }
        public string Other { get; set; }
    }
}
