// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ScoreSharpTestData.Models
{
    public partial class Usp_GetApplyCreditCardInfoWithParamsResult
    {
        public string Type { get; set; }
        public string Name { get; set; }
        public string StringValue { get; set; }
        public int? IntValue { get; set; }
        public string IsActive { get; set; }
    }
}
